[project]
name = "learn-jina-embedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.1",
    "numpy<2",
    "onnxruntime>=1.22.0",
    "torch>=2.7.1",
    "transformers>=4.53.0",
]
